import { describe, expect, it } from "vitest";

import materials from "../../src/data/source/materials.json";
import laws from "../../src/data/source/laws.json";
import resultClasses from "../../src/data/source/resultClasses.json";
import { BROWSER_RUNTIME_PACKET } from "../../src/application";
import { browserPacketHasCanonicalArt } from "../../src/application/browser/runtime-packet";
import { validateForgeResolverContext } from "../../src/domain/forge-runtime";
import type { Law, Material, ResultClass } from "../../src/data/schema/contracts";
import { buildBrowserRuntimePacket, readBrowserAssetAvailability, renderBrowserRuntimePacket } from "../../scripts/gen-browser-runtime-packet";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

describe("browser runtime packet", () => {
  const repositoryRoot = resolve(import.meta.dirname, "../..");
  const assetAvailability = readBrowserAssetAvailability(repositoryRoot);

  it("is the exact deterministic 52/21/34 projection used by the browser", () => {
    const expected = buildBrowserRuntimePacket(materials as Material[], laws as Law[], resultClasses as ResultClass[], assetAvailability);
    expect(BROWSER_RUNTIME_PACKET).toEqual(expected);
    expect(BROWSER_RUNTIME_PACKET.counts).toEqual({ materials: 52, laws: 21, resultClasses: 34 });
    expect(validateForgeResolverContext(BROWSER_RUNTIME_PACKET.resolverContext)).toEqual({ valid: true, errors: [] });
    expect(BROWSER_RUNTIME_PACKET.assetAvailability.canonicalCardCount).toBe(489);
    expect(BROWSER_RUNTIME_PACKET.assetAvailability.materialPairBitsetHex).toHaveLength(676);
    expect(browserPacketHasCanonicalArt(BROWSER_RUNTIME_PACKET, ["ore_still", "still_01"])).toBe(true);
    expect(browserPacketHasCanonicalArt(BROWSER_RUNTIME_PACKET, ["ore_still", "still_03"])).toBe(false);
  });

  it("keeps generated bytes fresh against the canonical sources", () => {
    const expected = renderBrowserRuntimePacket(buildBrowserRuntimePacket(materials as Material[], laws as Law[], resultClasses as ResultClass[], assetAvailability));
    const actual = readFileSync(resolve(import.meta.dirname, "../../src/application/browser/runtime-packet.generated.ts"), "utf8");
    expect(actual).toBe(expected);
  });
});
