import { lookup as dnsLookup } from "node:dns/promises";
import { execFileSync } from "node:child_process";
import { existsSync, lstatSync, readFileSync } from "node:fs";
import type { IncomingHttpHeaders } from "node:http";
import { request as httpsRequest } from "node:https";
import { isIP } from "node:net";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { DEFAULT_MAX_PNG_BYTES, acquireRunnerLock, assertNonOverlappingRoots, atomicWriteJson, atomicWriteVerifiedPng, backupVerifiedFile, inspectPng, safeResolve, verifyExistingPng } from "./filesystem";
import { T015_V2_JOURNAL_PATH, T015_V2_JOURNAL_SHA256, T015_V3_BINDING_PATH, T015_V3_PLAN_PATH, buildT015V3Forensics, buildT015V3Plan, isT015V3Authorized, loadPinnedT015V2Journal, loadT015V3Binding, renderT015CanonicalJson, renderT015V3Plan, sha256T015V3, t015V3PlanSha256, type T015V3Plan } from "./canonical-shard-1-recovery-v3";

const repositoryRoot = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
export const T015_V3_JOURNAL_PATH = "assets/runs/t015-canonical-shard-1/operations-v3.json" as const;
const LOCK_PATH = "assets/runs/t015-canonical-shard-1/operations-v3.lock";
const LOCAL_ROOT = "public/assets";
const BACKUP_ROOT = "assets/backups/t015-canonical-shard-1";
const MAX_STDIN_BYTES = 2 * 1024 * 1024;
const MAX_REDIRECTS = 3;
const DOWNLOAD_TIMEOUT_MS = 30_000;
const EXPECTED_MODEL = "nano_banana_flash";
const STATUSES = ["pending", "waiting", "queued", "in_progress", "ip_detect", "completed", "failed", "canceled", "nsfw", "ip_detected", "lookup_failed"] as const;
type WaitStatus = typeof STATUSES[number];

interface V3Job { index: number; asset_id: string; job_id: string; canonical_request_sha256: string }
interface RedactedJob { index: number; job_id: string; status: WaitStatus; model: string | null; type: "image"; download_available: boolean; lookup_retryable: boolean | null }
interface Recovery { asset_id: string; provider_job_index: number; provider_job_id: string; source: "V3_JOBS_WAIT_STDIN"; observed_at: string; local_relative_path: string; backup_relative_path: string; sha256: string; size_bytes: number; actual_width: number; actual_height: number; aspect_error_ppm: number; provider_native_unmodified: true }
type FailureStage = "JOBS_WAIT_JSON" | "JOBS_WAIT_TOPOLOGY" | "JOBS_WAIT_SUMMARY" | "JOBS_WAIT_SIGNAL" | "GENERATION_STATUS" | "MODEL" | "SECURE_DOWNLOAD" | "PNG_ATOMIC_STORE";
export interface T015V3Journal { schema_version: 3; journal_version: "t015-canonical-shard-1-operations-v3"; redacted: true; plan_sha256: string; immutable_forensics: { operations_v1_sha256: string; operations_v2_path: typeof T015_V2_JOURNAL_PATH; operations_v2_sha256: typeof T015_V2_JOURNAL_SHA256; v1_failure_code: "PROVIDER_RESPONSE_SIGNAL"; v2_failure_code: "RECOVERY_FAILED"; v2_failure_stage: "SECURE_DOWNLOAD"; sources_mutated: false }; run_state: "HOLD_FOR_FRESH_V3_APPROVAL" | "RECOVERY_ONLY" | "FAIL_STOP" | "HOLD_FOR_FUTURE_PAID_IMPLEMENTATION"; accounting: { legacy_cap_committed_decimal: "18.00"; provider_balance_delta_verified: false; future_additional_credit_cap_decimal: "480.00"; total_credit_cap_decimal: "498.00"; automatic_paid_retry_reserve_decimal: "0.00"; paid_retry_count: 0 }; legacy_recovery: { asset_ids: string[]; jobs: V3Job[]; migrated_at: string; new_paid_submit_allowed: false; polls: Array<{ observed_at: string; all_terminal: boolean; jobs: RedactedJob[] }>; recoveries: Recovery[]; failures: Array<{ code: "PROVIDER_RESPONSE_SIGNAL" | "UNKNOWN_PROVIDER_FIELD" | "GENERATION_FAILED" | "MODEL_DRIFT" | "RECOVERY_FAILED" | "FILE_CONFLICT"; observed_at: string; stage: FailureStage; automatic_paid_retry: false; paid_retry_count: 0; no_resubmit: true }> }; future: { slice: "12..331"; asset_count: 320; additional_credit_cap_decimal: "480.00"; implementation_state: "LOCKED_NOT_IMPLEMENTED"; paid_submit_path_present: false; authorization: null } }

export interface T015V3Address { address: string; family: 4 | 6 }
export interface T015V3FetchSpec { url: URL; hostname: string; servername: string; pinned: T015V3Address; signal: AbortSignal }
export interface T015V3Dependencies { resolve(hostname: string, signal: AbortSignal): Promise<readonly T015V3Address[]>; fetch(spec: T015V3FetchSpec): Promise<{ status: number; headers: IncomingHttpHeaders; bytes: Buffer; remoteAddress: string }>; timeout_ms?: number }

function ipv4(address: string): number[] | null { if (isIP(address) !== 4) return null; const bytes = address.split(".").map(Number); return bytes.length === 4 && bytes.every((byte) => Number.isInteger(byte) && byte >= 0 && byte <= 255) ? bytes : null; }
function ipv6Words(address: string): number[] | null { if (isIP(address) !== 6 || address.includes("%")) return null; let normalized = address.toLowerCase(); if (normalized.includes(".")) { const colon = normalized.lastIndexOf(":"); const tail = ipv4(normalized.slice(colon + 1)); if (colon < 0 || !tail) return null; normalized = `${normalized.slice(0, colon + 1)}${((tail[0] << 8) | tail[1]).toString(16)}:${((tail[2] << 8) | tail[3]).toString(16)}`; } const halves = normalized.split("::"); if (halves.length > 2) return null; const half = (value: string) => value === "" ? [] : value.split(":").every((item) => /^[a-f0-9]{1,4}$/.test(item)) ? value.split(":").map((item) => Number.parseInt(item, 16)) : null; const left = half(halves[0]); const right = half(halves[1] ?? ""); if (!left || !right) return null; if (halves.length === 1) return left.length === 8 ? left : null; const zeros = 8 - left.length - right.length; return zeros > 0 ? [...left, ...Array<number>(zeros).fill(0), ...right] : null; }
export function isPublicT015V3ResolvedAddress(item: T015V3Address): boolean { if (item.family === 4) { const b = ipv4(item.address); if (!b) return false; const [a, second, third] = b; return !(a === 0 || a === 10 || a === 127 || a >= 224 || (a === 100 && second >= 64 && second <= 127) || (a === 169 && second === 254) || (a === 172 && second >= 16 && second <= 31) || (a === 192 && second === 168) || (a === 192 && second === 0 && (third === 0 || third === 2)) || (a === 192 && second === 31 && third === 196) || (a === 192 && second === 52 && third === 193) || (a === 192 && second === 88 && third === 99) || (a === 192 && second === 175 && third === 48) || (a === 198 && (second === 18 || second === 19)) || (a === 198 && second === 51 && third === 100) || (a === 203 && second === 0 && third === 113)); } if (item.family !== 6) return false; const words = ipv6Words(item.address); if (!words || (words[0] & 0xe000) !== 0x2000) return false; const mapped = words.slice(0, 5).every((word) => word === 0) && words[5] === 0xffff; return !mapped && !(words[0] === 0x2001 && words[1] <= 0x01ff) && words[0] !== 0x2002 && words[0] !== 0x3fff; }
export function transportPeerMatchesT015V3Pin(remoteAddress: string, pinned: T015V3Address): boolean { if (pinned.family === 4) { const expected = ipv4(pinned.address); const direct = ipv4(remoteAddress); if (expected && direct) return expected.every((byte, index) => byte === direct[index]); const matched = /^::ffff:(\d{1,3}(?:\.\d{1,3}){3})$/i.exec(remoteAddress); const tail = matched ? ipv4(matched[1]) : null; return expected !== null && tail !== null && expected.every((byte, index) => byte === tail[index]); } const a = ipv6Words(remoteAddress); const b = ipv6Words(pinned.address); return a !== null && b !== null && a.every((word, index) => word === b[index]); }

function defaultFetch(spec: T015V3FetchSpec): Promise<{ status: number; headers: IncomingHttpHeaders; bytes: Buffer; remoteAddress: string }> { return new Promise((resolvePromise, reject) => { const request = httpsRequest({ protocol: "https:", hostname: spec.hostname, path: `${spec.url.pathname}${spec.url.search}`, method: "GET", port: 443, servername: spec.servername, rejectUnauthorized: true, signal: spec.signal, lookup: (_host, _options, callback) => callback(null, spec.pinned.address, spec.pinned.family) }, (response) => { const chunks: Buffer[] = []; let size = 0; response.on("data", (chunk: Buffer) => { size += chunk.length; if (size > DEFAULT_MAX_PNG_BYTES) request.destroy(new Error("FILE_TOO_LARGE")); else chunks.push(chunk); }); response.on("end", () => resolvePromise({ status: response.statusCode ?? 0, headers: response.headers, bytes: Buffer.concat(chunks), remoteAddress: response.socket.remoteAddress ?? "" })); }); request.on("error", reject); request.end(); }); }
const defaultDependencies: T015V3Dependencies = { resolve: async (hostname) => (await dnsLookup(hostname, { all: true, verbatim: true })).map((entry) => ({ address: entry.address, family: entry.family as 4 | 6 })), fetch: defaultFetch };
function approvedUrl(raw: unknown): URL { if (typeof raw !== "string" || raw.length > 16_384) throw new Error("DOWNLOAD"); const url = new URL(raw); const host = url.hostname.startsWith("[") ? url.hostname.slice(1, -1) : url.hostname; if (url.protocol !== "https:" || url.username || url.password || url.port || isIP(host) || !host.includes(".") || host === "localhost" || host.endsWith(".localhost") || !/^[a-z0-9.-]+$/i.test(host)) throw new Error("DOWNLOAD"); return url; }
function deadline<T>(promise: Promise<T>, signal: AbortSignal): Promise<T> { if (signal.aborted) return Promise.reject(new Error("DOWNLOAD")); return new Promise((resolvePromise, reject) => { const abort = () => reject(new Error("DOWNLOAD")); signal.addEventListener("abort", abort, { once: true }); promise.then((value) => { signal.removeEventListener("abort", abort); resolvePromise(value); }, reject); }); }
async function download(raw: string, deps: T015V3Dependencies): Promise<Buffer> { let url = approvedUrl(raw); for (let redirects = 0; redirects <= MAX_REDIRECTS; redirects += 1) { const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), deps.timeout_ms ?? DOWNLOAD_TIMEOUT_MS); try { const addresses = await deadline(deps.resolve(url.hostname, controller.signal), controller.signal); if (!addresses.length || addresses.some((address) => !isPublicT015V3ResolvedAddress(address))) throw new Error("DOWNLOAD"); const pinned = addresses[0]; const response = await deadline(deps.fetch({ url, hostname: url.hostname, servername: url.hostname, pinned, signal: controller.signal }), controller.signal); if (!transportPeerMatchesT015V3Pin(response.remoteAddress, pinned)) throw new Error("DOWNLOAD"); if ([301, 302, 303, 307, 308].includes(response.status)) { if (typeof response.headers.location !== "string" || redirects === MAX_REDIRECTS) throw new Error("DOWNLOAD"); url = approvedUrl(new URL(response.headers.location, url).toString()); continue; } const type = response.headers["content-type"]?.toString().split(";", 1)[0].trim().toLowerCase(); const length = response.headers["content-length"] === undefined ? null : Number(response.headers["content-length"]); if (response.status !== 200 || type !== "image/png" || response.bytes.length > DEFAULT_MAX_PNG_BYTES || (length !== null && (!Number.isSafeInteger(length) || length < 1 || length !== response.bytes.length))) throw new Error("DOWNLOAD"); return response.bytes; } finally { clearTimeout(timer); } } throw new Error("DOWNLOAD"); }

function timestamp(value: string): string { if (!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{3})?Z$/.test(value) || !Number.isFinite(Date.parse(value))) throw new Error("invalid T015 v3 timestamp"); return value; }
function exactKeys(value: Record<string, unknown>, required: readonly string[], allowed = required): boolean { return required.every((key) => key in value) && Object.keys(value).every((key) => allowed.includes(key)); }
function journalPath(root: string): string { return safeResolve(root, T015_V3_JOURNAL_PATH); }
function safeJournal(journal: T015V3Journal): void { const bytes = JSON.stringify(journal); if (/https?:\/\//i.test(bytes) || /result_url|thumbnail_url|raw_error|hostname/i.test(bytes)) throw new Error("T015 v3 journal is not URL-free"); }
function writeJournal(root: string, journal: T015V3Journal): void { safeJournal(journal); atomicWriteJson(root, T015_V3_JOURNAL_PATH, journal); }
function initialJournal(root: string, plan: T015V3Plan, at: string): T015V3Journal { const v2 = loadPinnedT015V2Journal(root); const forensics = buildT015V3Forensics(root); return { schema_version: 3, journal_version: "t015-canonical-shard-1-operations-v3", redacted: true, plan_sha256: t015V3PlanSha256(plan), immutable_forensics: { operations_v1_sha256: forensics.immutable_sources.operations_v1.sha256, operations_v2_path: T015_V2_JOURNAL_PATH, operations_v2_sha256: T015_V2_JOURNAL_SHA256, v1_failure_code: "PROVIDER_RESPONSE_SIGNAL", v2_failure_code: "RECOVERY_FAILED", v2_failure_stage: "SECURE_DOWNLOAD", sources_mutated: false }, run_state: "RECOVERY_ONLY", accounting: { legacy_cap_committed_decimal: "18.00", provider_balance_delta_verified: false, future_additional_credit_cap_decimal: "480.00", total_credit_cap_decimal: "498.00", automatic_paid_retry_reserve_decimal: "0.00", paid_retry_count: 0 }, legacy_recovery: { asset_ids: v2.legacy_recovery.jobs.map((job) => job.asset_id), jobs: v2.legacy_recovery.jobs.map(({ index, asset_id, job_id, canonical_request_sha256 }) => ({ index, asset_id, job_id, canonical_request_sha256 })), migrated_at: timestamp(at), new_paid_submit_allowed: false, polls: [], recoveries: [], failures: [] }, future: { slice: "12..331", asset_count: 320, additional_credit_cap_decimal: "480.00", implementation_state: "LOCKED_NOT_IMPLEMENTED", paid_submit_path_present: false, authorization: null } }; }
export function validateT015V3Journal(journal: T015V3Journal, root: string, plan: T015V3Plan): void { loadPinnedT015V2Journal(root); safeJournal(journal); const baseline = initialJournal(root, plan, journal.legacy_recovery.migrated_at); if (journal.schema_version !== 3 || journal.journal_version !== baseline.journal_version || journal.plan_sha256 !== baseline.plan_sha256 || JSON.stringify(journal.immutable_forensics) !== JSON.stringify(baseline.immutable_forensics) || JSON.stringify(journal.accounting) !== JSON.stringify(baseline.accounting) || JSON.stringify(journal.legacy_recovery.asset_ids) !== JSON.stringify(baseline.legacy_recovery.asset_ids) || JSON.stringify(journal.legacy_recovery.jobs) !== JSON.stringify(baseline.legacy_recovery.jobs) || journal.legacy_recovery.new_paid_submit_allowed !== false || JSON.stringify(journal.future) !== JSON.stringify(baseline.future)) throw new Error("T015 v3 journal binding changed"); const ids = new Set<string>(); for (const recovery of journal.legacy_recovery.recoveries) { if (ids.has(recovery.asset_id) || !journal.legacy_recovery.jobs.some((job) => job.asset_id === recovery.asset_id) || recovery.provider_native_unmodified !== true) throw new Error("T015 v3 recovery binding changed"); verifyExistingPng(resolve(root, LOCAL_ROOT), recovery.local_relative_path, "3:4", recovery.sha256, DEFAULT_MAX_PNG_BYTES, 5000); verifyExistingPng(resolve(root, BACKUP_ROOT), recovery.backup_relative_path, "3:4", recovery.sha256, DEFAULT_MAX_PNG_BYTES, 5000); ids.add(recovery.asset_id); } if (journal.legacy_recovery.recoveries.length === 12 ? journal.run_state !== "HOLD_FOR_FUTURE_PAID_IMPLEMENTATION" : !["RECOVERY_ONLY", "FAIL_STOP"].includes(journal.run_state)) throw new Error("T015 v3 state changed"); }
function readJournal(root: string, plan: T015V3Plan): T015V3Journal { const bytes = readFileSync(journalPath(root), "utf8"); const value = JSON.parse(bytes) as T015V3Journal; if (bytes !== renderT015CanonicalJson(value)) throw new Error("T015 v3 journal is not canonical"); validateT015V3Journal(value, root, plan); return value; }
function fail(root: string, journal: T015V3Journal, code: T015V3Journal["legacy_recovery"]["failures"][number]["code"], stage: FailureStage, at: string): never { journal.legacy_recovery.failures.push({ code, observed_at: timestamp(at), stage, automatic_paid_retry: false, paid_retry_count: 0, no_resubmit: true }); journal.run_state = "FAIL_STOP"; writeJournal(root, journal); throw new Error(`${code}: ${stage}; exact 12 legacy jobs preserved; no paid submit or retry`); }

function recoveryRecord(plan: T015V3Plan, job: V3Job, checked: ReturnType<typeof inspectPng>, at: string, source: Recovery["source"]): Recovery { const asset = plan.assets[job.index]; return { asset_id: job.asset_id, provider_job_index: job.index, provider_job_id: job.job_id, source, observed_at: at, local_relative_path: asset.path, backup_relative_path: asset.path, sha256: checked.sha256, size_bytes: checked.size, actual_width: checked.width, actual_height: checked.height, aspect_error_ppm: checked.aspect_error_ppm, provider_native_unmodified: true }; }
function ingest(root: string, journal: T015V3Journal, plan: T015V3Plan, job: V3Job, bytes: Buffer, at: string): void { try { const asset = plan.assets[job.index]; const local = atomicWriteVerifiedPng(resolve(root, LOCAL_ROOT), asset.path, bytes, "3:4", DEFAULT_MAX_PNG_BYTES, 5000); const backup = backupVerifiedFile(resolve(root, LOCAL_ROOT), resolve(root, BACKUP_ROOT), asset.path, local.sha256, "3:4", DEFAULT_MAX_PNG_BYTES, 5000); if (local.sha256 !== backup.sha256) throw new Error("conflict"); journal.legacy_recovery.recoveries.push(recoveryRecord(plan, job, local, at, "V3_JOBS_WAIT_STDIN")); if (journal.legacy_recovery.recoveries.length === 12) journal.run_state = "HOLD_FOR_FUTURE_PAID_IMPLEMENTATION"; writeJournal(root, journal); } catch { fail(root, journal, "RECOVERY_FAILED", "PNG_ATOMIC_STORE", at); } }

export function runT015V3OpsInternal(args: readonly string[], root: string, plan: T015V3Plan): Record<string, unknown> { const lock = acquireRunnerLock(root, LOCK_PATH); try { const command = args[0]; if (command === "migrate") { if (args.length !== 3 || args[1] !== "--observed-at") throw new Error("usage: recovery-v3 migrate --observed-at <timestamp>"); const at = timestamp(args[2]); if (existsSync(journalPath(root))) return { command, state: readJournal(root, plan).run_state, idempotent: true, new_paid_submit: false }; assertNonOverlappingRoots(resolve(root, LOCAL_ROOT), resolve(root, BACKUP_ROOT)); const journal = initialJournal(root, plan, at); writeJournal(root, journal); return { command, state: journal.run_state, legacy_jobs: 12, v2_journal_sha256: T015_V2_JOURNAL_SHA256, new_paid_submit: false, paid_retry_count: 0 }; } const journal = readJournal(root, plan); if (command === "jobs-request") return { jobs: journal.legacy_recovery.jobs.map(({ index, job_id }) => ({ index, job_id })), new_paid_submit: false, paid_retry_count: 0 }; if (command === "status") return { state: journal.run_state, legacy_jobs: 12, recovered: journal.legacy_recovery.recoveries.length, failures: journal.legacy_recovery.failures.length, v1_v2_forensics_preserved: true, future_paid_assets: 320, future_paid_locked: true, paid_submit_path_present: false, paid_retry_count: 0 }; throw new Error("usage: recovery-v3 <migrate|jobs-request|status|jobs-handoff>"); } finally { lock.release(); } }

export async function runT015V3JobsHandoffInternal(args: readonly string[], stdinJson: string, root: string, plan: T015V3Plan, deps: T015V3Dependencies = defaultDependencies): Promise<Record<string, unknown>> { if (args.length !== 3 || args[0] !== "jobs-handoff" || args[1] !== "--observed-at") throw new Error("usage: recovery-v3 jobs-handoff --observed-at <timestamp>"); if (Buffer.byteLength(stdinJson) > MAX_STDIN_BYTES) throw new Error("T015 v3 stdin too large"); const at = timestamp(args[2]); const lock = acquireRunnerLock(root, LOCK_PATH); try { const journal = readJournal(root, plan); if (!["RECOVERY_ONLY", "FAIL_STOP"].includes(journal.run_state)) throw new Error("T015 v3 recovery is not open"); let raw: unknown; try { raw = JSON.parse(stdinJson); } catch { fail(root, journal, "UNKNOWN_PROVIDER_FIELD", "JOBS_WAIT_JSON", at); } if (!raw || typeof raw !== "object" || Array.isArray(raw)) fail(root, journal, "UNKNOWN_PROVIDER_FIELD", "JOBS_WAIT_JSON", at); const response = raw as Record<string, unknown>; if (!exactKeys(response, ["all_terminal", "jobs", "summary"], ["all_terminal", "jobs", "summary", "poll_after_seconds", "timed_out", "aborted"]) || typeof response.all_terminal !== "boolean" || !Array.isArray(response.jobs) || !response.summary || typeof response.summary !== "object" || Array.isArray(response.summary) || ("timed_out" in response && typeof response.timed_out !== "boolean") || ("aborted" in response && typeof response.aborted !== "boolean") || ("poll_after_seconds" in response && (typeof response.poll_after_seconds !== "number" || !Number.isFinite(response.poll_after_seconds) || response.poll_after_seconds < 0))) fail(root, journal, "UNKNOWN_PROVIDER_FIELD", "JOBS_WAIT_TOPOLOGY", at); if (response.timed_out === true || response.aborted === true) fail(root, journal, "PROVIDER_RESPONSE_SIGNAL", "JOBS_WAIT_SIGNAL", at);
    const urls = new Map<string, string>(); const redacted: RedactedJob[] = []; const seen = new Set<string>(); let valid = response.jobs.length === 12;
    for (const item of response.jobs as unknown[]) { if (!item || typeof item !== "object" || Array.isArray(item)) { valid = false; continue; } const job = item as Record<string, unknown>; if (!exactKeys(job, ["index", "job_id", "status", "type"], ["index", "job_id", "status", "type", "model", "result_url", "retryable"])) { valid = false; continue; } const expected = journal.legacy_recovery.jobs.find((candidate) => candidate.index === job.index && candidate.job_id === job.job_id); const status = job.status as WaitStatus; if (!expected || seen.has(expected.job_id) || !STATUSES.includes(status) || job.type !== "image") { valid = false; continue; } seen.add(expected.job_id); const hasRetryable = "retryable" in job; if ((status === "lookup_failed") !== hasRetryable || (hasRetryable && typeof job.retryable !== "boolean")) { valid = false; continue; } const model = typeof job.model === "string" ? job.model : null; const url = typeof job.result_url === "string" ? job.result_url : null; if ((status === "completed") !== (url !== null) || (status === "completed") !== (model !== null) || (status !== "completed" && ("result_url" in job || "model" in job))) { valid = false; continue; } if (url) urls.set(expected.asset_id, url); redacted.push({ index: expected.index, job_id: expected.job_id, status, model, type: "image", download_available: url !== null, lookup_retryable: hasRetryable ? job.retryable as boolean : null }); }
    redacted.sort((a, b) => a.index - b.index); if (!valid || redacted.length !== 12) fail(root, journal, "UNKNOWN_PROVIDER_FIELD", "JOBS_WAIT_TOPOLOGY", at); const active = ["pending", "waiting", "queued", "in_progress", "ip_detect"]; const failed = ["failed", "canceled", "nsfw", "ip_detected"]; const derived = { active: redacted.filter((job) => active.includes(job.status)).length, completed: redacted.filter((job) => job.status === "completed").length, errors: redacted.filter((job) => job.status === "lookup_failed").length, failed: redacted.filter((job) => failed.includes(job.status)).length, total: 12 }; const summary = response.summary as Record<string, unknown>; if (!exactKeys(summary, ["active", "completed", "errors", "failed", "total"]) || JSON.stringify(summary) !== JSON.stringify(derived)) fail(root, journal, "UNKNOWN_PROVIDER_FIELD", "JOBS_WAIT_SUMMARY", at); journal.legacy_recovery.polls.push({ observed_at: at, all_terminal: response.all_terminal as boolean, jobs: redacted }); journal.run_state = "RECOVERY_ONLY"; writeJournal(root, journal); if (redacted.some((job) => job.status === "lookup_failed" && job.lookup_retryable === true) || response.all_terminal !== true) return { state: "RECOVERY_ONLY", repoll_same_jobs_only: true, new_paid_submit: false }; if (redacted.some((job) => job.status !== "completed")) fail(root, journal, "GENERATION_FAILED", "GENERATION_STATUS", at); if (redacted.some((job) => job.model !== EXPECTED_MODEL)) fail(root, journal, "MODEL_DRIFT", "MODEL", at);
    for (const job of journal.legacy_recovery.jobs) { if (journal.legacy_recovery.recoveries.some((recovery) => recovery.asset_id === job.asset_id)) continue; const url = urls.get(job.asset_id); if (!url) fail(root, journal, "RECOVERY_FAILED", "SECURE_DOWNLOAD", at); let bytes: Buffer; try { bytes = await download(url, deps); } catch { fail(root, journal, "RECOVERY_FAILED", "SECURE_DOWNLOAD", at); } ingest(root, journal, plan, job, bytes, at); }
    journal.run_state = "HOLD_FOR_FUTURE_PAID_IMPLEMENTATION"; writeJournal(root, journal); return { state: journal.run_state, recovered: 12, v1_v2_forensics_preserved: true, future_paid_locked: true, paid_submit_path_present: false, new_paid_submit: false, paid_retry_count: 0 }; } finally { lock.release(); } }

export function assertT015V3CommittedClean(root: string): void { const binding = loadT015V3Binding(root); const paths = [T015_V3_BINDING_PATH, T015_V3_PLAN_PATH, ...Object.values(binding.files).map(({ path }) => path)]; for (const path of paths) { try { execFileSync("git", ["ls-files", "--error-unmatch", "--", path], { cwd: root, stdio: "ignore" }); execFileSync("git", ["diff", "--quiet", "HEAD", "--", path], { cwd: root, stdio: "ignore" }); const committed = execFileSync("git", ["show", `HEAD:${path}`], { cwd: root }); if (sha256T015V3(committed) !== sha256T015V3(readFileSync(resolve(root, path)))) throw new Error("not clean"); } catch { throw new Error(`T015 v3 production binding is not committed-clean: ${path}`); } } }
function productionPlan(): T015V3Plan { const plan = buildT015V3Plan(repositoryRoot); const bytes = readFileSync(resolve(repositoryRoot, T015_V3_PLAN_PATH), "utf8"); if (bytes !== renderT015V3Plan(plan)) throw new Error("T015 v3 bound plan changed"); if (!isT015V3Authorized(repositoryRoot, plan)) throw new Error("T015 v3 fresh approval is missing; prior approvals are not inherited"); assertT015V3CommittedClean(repositoryRoot); return plan; }
export function runT015V3Ops(args: readonly string[]): Record<string, unknown> { return runT015V3OpsInternal(args, repositoryRoot, productionPlan()); }
export function runT015V3JobsHandoff(args: readonly string[], stdin: string): Promise<Record<string, unknown>> { return runT015V3JobsHandoffInternal(args, stdin, repositoryRoot, productionPlan(), defaultDependencies); }
export function tombstoneT015V1PaidRoute(): never { throw new Error("T015 v1 paid route is tombstoned after immutable failures; use approval-gated recovery-v3 only"); }
