import { createHash } from "node:crypto";
import { existsSync, lstatSync, readFileSync } from "node:fs";
import { resolve } from "node:path";

import {
  T015_CONTRACT_SHA256,
  T015_T014_APPROVAL_SHA256,
  canonicalJsonT015,
  renderT015CanonicalJson,
  type T015V2CanonicalShardPlan,
} from "./canonical-shard-1-v1-continuation-v2";

export { renderT015CanonicalJson } from "./canonical-shard-1-v1-continuation-v2";

export const T015_V3_PLAN_PATH = "assets/manifests/canonical-shard-1-v3.plan.json" as const;
export const T015_V3_BINDING_PATH = "assets/manifests/t015-implementation-binding-v3.json" as const;
export const T015_V3_RISK_PATH = "assets/evidence/t015-canonical-shard-1-risk-disclosure-v3.json" as const;
export const T015_V3_SCHEMA_PATH = "assets/evidence/t015-higgsfield-schema-v3.json" as const;
export const T015_V3_FORENSICS_PATH = "assets/evidence/t015-canonical-shard-1-v2-forensic-migration.json" as const;
export const T015_V3_PENDING_PATH = "assets/evidence/t015-canonical-shard-1-disclosure-presentation-v3.pending.json" as const;
export const T015_V3_PRESENTATION_PATH = "assets/evidence/t015-canonical-shard-1-disclosure-presentation-v3.json" as const;
export const T015_V3_APPROVAL_PATH = "assets/evidence/t015-canonical-shard-1-approval-v3.json" as const;
export const T015_V3_CONTROLLER_DISCLOSURE_PATH = "assets/evidence/t015-controller-disclosure-attestation-v3.json" as const;
export const T015_V3_CONTROLLER_APPROVAL_PATH = "assets/evidence/t015-controller-approval-attestation-v3.json" as const;
export const T015_V3_REVOCATION_PATH = "assets/manifests/t015-legacy-production-revocation-v3.json" as const;
export const T015_V2_JOURNAL_PATH = "assets/runs/t015-canonical-shard-1/operations-v2.json" as const;
export const T015_V1_JOURNAL_PATH = "assets/runs/t015-canonical-shard-1/operations-v1.json" as const;
export const T015_V2_JOURNAL_SHA256 = "ff85d69888cc023c0cbd7f54e043239fdd47b28a7393870f96e87f58b3663fee" as const;
export const T015_V2_PLAN_SHA256 = "49809ecf7f10fb590014b023b2c9328415fedae36be83bb883a4e3c090d45e4b" as const;
export const T015_V2_PLAN_PATH = "assets/evidence/t015-forensic-canonical-shard-1-v2.plan.json" as const;
export const T015_V1_JOURNAL_SHA256 = "81d7ab7abdadbf86ee420953690550b62621910907fd9bb11cd8ccb19cf0d6f5" as const;
export const T015_V3_EXACT_APPROVAL_PHRASE = "위 재복구 위험을 확인했고 T015 기존 12개 job ID의 무과금 v3 복구와 CANONICAL 12..331 정확히 320장의 추가 480.00 credits 상한(이미 사용 처리 18.00, 누적 상한 498.00), 자동 유료 재시도 0을 승인합니다." as const;
export const T015_V3_RISK_TEXT = `T015 CANONICAL 0..331 총 332장과 누적 498.00 credits 상한은 유지됩니다. index 0..11의 첫 12장은 단 한 번 제출되어 정확히 12개의 확정 job ID가 있으며 18.00 credits를 누적 상한에서 사용 처리하지만 provider balance delta는 아직 검증되지 않았습니다. v1 복구는 PROVIDER_RESPONSE_SIGNAL로, v2 첫 다운로드는 SECURE_DOWNLOAD_FAILED로 각각 중단됐고 operations-v1 SHA-256 ${T015_V1_JOURNAL_SHA256} 및 operations-v2 SHA-256 ${T015_V2_JOURNAL_SHA256} 바이트를 불변 포렌식으로 보존합니다. v2 실패는 DNS가 반환한 실제 CloudFront 공개 IPv4가 아니라 Node TLS socket의 동일 IPv4-mapped remoteAddress 표기를 거부했을 가능성이 높다는 로컬 코드·저널 기반 추론이며 아직 원격으로 재검증하지 않았습니다. v3는 resolver가 반환한 IPv4-mapped IPv6를 계속 거부하되, resolver가 고정한 정확한 공개 IPv4와 transport remoteAddress의 ::ffff:IPv4 tail이 바이트 단위로 같을 때만 동일 peer로 허용합니다. jobs_wait는 type=image를 필수로 하고 retryable 필드의 존재는 lookup_failed 상태에서만 boolean으로 허용합니다. signed URL·redirect URL·provider raw error·host는 journal, evidence, stdout 및 실패 stage에 기록하지 않습니다. 기존 public 또는 backup PNG가 유효하게 남은 crash window는 동일 해시를 확인해 반대편을 원자적으로 보충하고, 양쪽 충돌은 fail-stop합니다. v3 복구는 기존 12개 job ID의 무과금 조회·다운로드만 제공하고 generate_image, generate_image_batch, 유료 재제출 및 자동 유료 재시도 경로를 제공하지 않습니다. 나머지 CANONICAL 12..331 정확히 320장은 추가 480.00 credits 한도로 계획에만 잠기며 이 구현에는 유료 제출 경로가 없습니다. v1/v2 승인 또는 기존 일반 승인은 상속되지 않습니다. v3 production 복구는 이 고지 뒤의 새 정확 승인과 커밋된 clean runtime binding을 모두 요구합니다. T016, index 332 이후, materials, hearts, world 자산은 제외됩니다. 새 승인은 정확히 “${T015_V3_EXACT_APPROVAL_PHRASE}”로만 기록합니다.` as const;

export const T015_V3_RUNTIME_FILES = {
  controller: "scripts/assets/canonical-shard-1-recovery-v3-controller.ts",
  preparation: "scripts/assets/canonical-shard-1-recovery-v3-cli.ts",
  recovery: "scripts/assets/canonical-shard-1-recovery-v3-ops.ts",
  contract: "scripts/assets/canonical-shard-1-recovery-v3.ts",
  v2_plan_builder: "scripts/assets/canonical-shard-1-v1-continuation-v2.ts",
  legacy_plan_builder: "scripts/assets/canonical-shard-1-v1.ts",
  filesystem: "scripts/assets/filesystem.ts",
  filesystem_types: "scripts/assets/types.ts",
  schema_contracts: "src/data/schema/contracts.ts",
  package_json: "package.json",
  package_lock: "package-lock.json",
  legacy_production_revocation: T015_V3_REVOCATION_PATH,
} as const;

export function sha256T015V3(value: string | Uint8Array): string { return createHash("sha256").update(value).digest("hex"); }
function canonical(value: unknown): string { return canonicalJsonT015(value); }
function readRegular(root: string, path: string): Buffer { const target = resolve(root, path); if (!existsSync(target) || lstatSync(target).isSymbolicLink() || !lstatSync(target).isFile()) throw new Error(`T015 v3 source is not a regular file: ${path}`); return readFileSync(target); }

export interface T015V3Binding { schema_version: 3; manifest_version: "t015-implementation-binding-v3"; issue_contract_sha256: typeof T015_CONTRACT_SHA256; files: Record<keyof typeof T015_V3_RUNTIME_FILES, { path: string; sha256: string }> }
export function buildT015V3Binding(root: string): T015V3Binding { return { schema_version: 3, manifest_version: "t015-implementation-binding-v3", issue_contract_sha256: T015_CONTRACT_SHA256, files: Object.fromEntries(Object.entries(T015_V3_RUNTIME_FILES).map(([key, path]) => [key, { path, sha256: sha256T015V3(readRegular(root, path)) }])) as T015V3Binding["files"] }; }
export function loadT015V3Binding(root: string): T015V3Binding { const v1Bytes = readRegular(root, T015_V1_JOURNAL_PATH); if (sha256T015V3(v1Bytes) !== T015_V1_JOURNAL_SHA256) throw new Error("T015 v3 pinned operations-v1 changed"); const bytes = readRegular(root, T015_V3_BINDING_PATH).toString("utf8"); const value = JSON.parse(bytes) as T015V3Binding; const expected = buildT015V3Binding(root); if (bytes !== renderT015CanonicalJson(value) || canonical(value) !== canonical(expected)) throw new Error("T015 v3 implementation binding changed"); return value; }

export interface T015V3Forensics { schema_version: 3; evidence_version: "t015-canonical-shard-1-v2-forensic-migration"; secret_free: true; immutable_sources: { operations_v1: { path: string; sha256: typeof T015_V1_JOURNAL_SHA256 }; operations_v2: { path: typeof T015_V2_JOURNAL_PATH; sha256: typeof T015_V2_JOURNAL_SHA256 }; v2_plan: { path: string; sha256: typeof T015_V2_PLAN_SHA256 } }; observed: { asset_slice: "0..11"; asset_count: 12; exact_job_id_list_sha256: string; completed_count: 12; type_image_count: 12; v1_failure_code: "PROVIDER_RESPONSE_SIGNAL"; v2_failure_code: "RECOVERY_FAILED"; v2_failure_stage: "SECURE_DOWNLOAD"; v2_recovery_count: 0; paid_retry_count: 0 }; policy: { mutate_v1_or_v2_journals: false; exact_existing_job_ids_only: true; paid_submit_path_present: false } }

interface V2Journal { journal_version: string; plan_sha256: string; run_state: string; immutable_legacy_journal: { sha256: string }; accounting: { paid_retry_count: number }; legacy_recovery: { exact_job_id_list_sha256: string; jobs: Array<{ index: number; asset_id: string; job_id: string; canonical_request_sha256: string }>; polls: Array<{ jobs: Array<{ status: string; type: string }> }>; recoveries: unknown[]; failures: Array<{ code: string; facts: Record<string, unknown> }> } }
export function loadPinnedT015V2Journal(root: string): V2Journal { const bytes = readRegular(root, T015_V2_JOURNAL_PATH); if (sha256T015V3(bytes) !== T015_V2_JOURNAL_SHA256) throw new Error("T015 v3 pinned operations-v2 changed"); const value = JSON.parse(bytes.toString("utf8")) as V2Journal; const poll = value.legacy_recovery.polls[0]; const failure = value.legacy_recovery.failures[0]; if (value.journal_version !== "t015-canonical-shard-1-operations-v2" || value.plan_sha256 !== T015_V2_PLAN_SHA256 || value.run_state !== "FAIL_STOP" || value.immutable_legacy_journal.sha256 !== T015_V1_JOURNAL_SHA256 || value.accounting.paid_retry_count !== 0 || value.legacy_recovery.jobs.length !== 12 || !poll || poll.jobs.length !== 12 || poll.jobs.some((job) => job.status !== "completed" || job.type !== "image") || value.legacy_recovery.recoveries.length !== 0 || value.legacy_recovery.failures.length !== 1 || failure.code !== "RECOVERY_FAILED" || failure.facts.reason !== "SECURE_DOWNLOAD_FAILED") throw new Error("T015 v3 operations-v2 forensic invariants changed"); return value; }
export function buildT015V3Forensics(root: string): T015V3Forensics { const v2 = loadPinnedT015V2Journal(root); return { schema_version: 3, evidence_version: "t015-canonical-shard-1-v2-forensic-migration", secret_free: true, immutable_sources: { operations_v1: { path: "assets/runs/t015-canonical-shard-1/operations-v1.json", sha256: T015_V1_JOURNAL_SHA256 }, operations_v2: { path: T015_V2_JOURNAL_PATH, sha256: T015_V2_JOURNAL_SHA256 }, v2_plan: { path: "assets/manifests/canonical-shard-1-v2.plan.json", sha256: T015_V2_PLAN_SHA256 } }, observed: { asset_slice: "0..11", asset_count: 12, exact_job_id_list_sha256: v2.legacy_recovery.exact_job_id_list_sha256, completed_count: 12, type_image_count: 12, v1_failure_code: "PROVIDER_RESPONSE_SIGNAL", v2_failure_code: "RECOVERY_FAILED", v2_failure_stage: "SECURE_DOWNLOAD", v2_recovery_count: 0, paid_retry_count: 0 }, policy: { mutate_v1_or_v2_journals: false, exact_existing_job_ids_only: true, paid_submit_path_present: false } }; }

export function buildT015V3Risk() { return { schema_version: 3, evidence_version: "t015-canonical-shard-1-risk-disclosure-v3", issue_number: 17, issue_contract_sha256: T015_CONTRACT_SHA256, secret_free: true, disclosure_text_ko: T015_V3_RISK_TEXT, disclosure_text_sha256: sha256T015V3(T015_V3_RISK_TEXT), scope: approvalScope() }; }
export function buildT015V3Schema() { return { schema_version: 3, evidence_version: "t015-higgsfield-schema-v3", source: "pinned T015 v1/v2 observations and local transport correction", secret_free: true, jobs_wait: { expected_type: "image", type_required: true, retryable_presence_only_for_status: "lookup_failed", retryable_value_type: "boolean", unknown_optional_signals_fail_stop: true }, secure_download: { resolver_mapped_ipv6_allowed: false, resolver_public_ipv4_allowed: true, transport_ipv4_mapped_peer_allowed_only_for_exact_pinned_ipv4_tail: true, redirects_revalidated_and_rebound: true, url_or_host_diagnostics_persisted: false }, recovery: { exact_existing_jobs: 12, paid_submit_path_present: false, reconcile_local_backup_crash_windows: true } }; }
export function approvalScope() { return { category: "CANONICAL", recovery_slice: "0..11", recovery_asset_count: 12, recovery_paid_submit_allowed: false, future_paid_slice: "12..331", future_paid_asset_count: 320, future_additional_credit_cap_decimal: "480.00", legacy_cap_committed_decimal: "18.00", total_credit_cap_decimal: "498.00", automatic_paid_retry_reserve_decimal: "0.00", t016_or_other_assets_allowed: false }; }

export type T015V3Plan = Omit<T015V2CanonicalShardPlan, "schema_version" | "plan_version" | "state" | "sources" | "approval_gate"> & { schema_version: 3; plan_version: "t015-canonical-shard-1-v3"; state: "HOLD_FOR_FRESH_V3_APPROVAL"; sources: T015V2CanonicalShardPlan["sources"] & { failed_v2_journal: { path: typeof T015_V2_JOURNAL_PATH; sha256: typeof T015_V2_JOURNAL_SHA256 }; v3_forensics: { path: typeof T015_V3_FORENSICS_PATH; sha256: string }; risk_disclosure: { path: typeof T015_V3_RISK_PATH; sha256: string; text_sha256: string }; provider_schema: { path: typeof T015_V3_SCHEMA_PATH; sha256: string }; implementation_binding: { path: typeof T015_V3_BINDING_PATH; sha256: string; files: T015V3Binding["files"] } }; approval_gate: { pending_disclosure_packet_path: typeof T015_V3_PENDING_PATH; disclosure_presentation_path: typeof T015_V3_PRESENTATION_PATH; controller_approval_attestation_path: typeof T015_V3_CONTROLLER_APPROVAL_PATH; approval_path: typeof T015_V3_APPROVAL_PATH; status: "MISSING_NOT_AUTHORIZED"; exact_phrase: typeof T015_V3_EXACT_APPROVAL_PHRASE; prior_t015_v1_or_v2_approval_inherited: false; committed_clean_runtime_binding_required: true } };
function loadPinnedV2Plan(root: string): T015V2CanonicalShardPlan { const bytes = readRegular(root, T015_V2_PLAN_PATH); if (sha256T015V3(bytes) !== T015_V2_PLAN_SHA256) throw new Error("T015 v3 pinned v2 plan changed"); const value = JSON.parse(bytes.toString("utf8")) as T015V2CanonicalShardPlan; if (bytes.toString("utf8") !== renderT015CanonicalJson(value) || value.schema_version !== 2 || value.plan_version !== "t015-canonical-shard-1-v2" || value.assets.length !== 332 || value.legacy_recovery.batch.size !== 12 || value.batches.reduce((sum, batch) => sum + batch.size, 0) !== 320) throw new Error("T015 v3 pinned v2 plan invariants changed"); return value; }
export function buildT015V3Plan(root: string): T015V3Plan { const base = loadPinnedV2Plan(root); const risk = buildT015V3Risk(); const schema = buildT015V3Schema(); const forensics = buildT015V3Forensics(root); const binding = loadT015V3Binding(root); return { ...base, schema_version: 3, plan_version: "t015-canonical-shard-1-v3", state: "HOLD_FOR_FRESH_V3_APPROVAL", sources: { ...base.sources, failed_v2_journal: { path: T015_V2_JOURNAL_PATH, sha256: T015_V2_JOURNAL_SHA256 }, v3_forensics: { path: T015_V3_FORENSICS_PATH, sha256: sha256T015V3(renderT015CanonicalJson(forensics)) }, risk_disclosure: { path: T015_V3_RISK_PATH, sha256: sha256T015V3(renderT015CanonicalJson(risk)), text_sha256: risk.disclosure_text_sha256 }, provider_schema: { path: T015_V3_SCHEMA_PATH, sha256: sha256T015V3(renderT015CanonicalJson(schema)) }, implementation_binding: { path: T015_V3_BINDING_PATH, sha256: sha256T015V3(renderT015CanonicalJson(binding)), files: binding.files } }, approval_gate: { pending_disclosure_packet_path: T015_V3_PENDING_PATH, disclosure_presentation_path: T015_V3_PRESENTATION_PATH, controller_approval_attestation_path: T015_V3_CONTROLLER_APPROVAL_PATH, approval_path: T015_V3_APPROVAL_PATH, status: "MISSING_NOT_AUTHORIZED", exact_phrase: T015_V3_EXACT_APPROVAL_PHRASE, prior_t015_v1_or_v2_approval_inherited: false, committed_clean_runtime_binding_required: true } } as T015V3Plan; }
export function renderT015V3Plan(plan: T015V3Plan): string { return renderT015CanonicalJson(plan); }
export function t015V3PlanSha256(plan: T015V3Plan): string { return sha256T015V3(renderT015V3Plan(plan)); }
export function buildT015V3Pending(root: string, plan: T015V3Plan) { const risk = buildT015V3Risk(); const schema = buildT015V3Schema(); const forensics = buildT015V3Forensics(root); const binding = loadT015V3Binding(root); return { schema_version: 3, artifact_version: "t015-canonical-shard-1-disclosure-presentation-v3-pending", status: "PENDING_PRESENTATION_NOT_AUTHORIZED", secret_free: true, plan_sha256: t015V3PlanSha256(plan), risk_disclosure_evidence_sha256: sha256T015V3(renderT015CanonicalJson(risk)), risk_disclosure_text_sha256: risk.disclosure_text_sha256, provider_schema_evidence_sha256: sha256T015V3(renderT015CanonicalJson(schema)), v2_forensics_sha256: sha256T015V3(renderT015CanonicalJson(forensics)), failed_v2_journal_sha256: T015_V2_JOURNAL_SHA256, implementation_binding_sha256: sha256T015V3(renderT015CanonicalJson(binding)), implementation_files: binding.files, t014_approval_sha256: T015_T014_APPROVAL_SHA256, exact_approval_phrase_required: T015_V3_EXACT_APPROVAL_PHRASE, prior_t015_v1_or_v2_approval_inherited: false, committed_clean_runtime_binding_required: true, paid_submit_path_present: false, authorized: false }; }

function canonicalFile<T>(root: string, path: string): { value: T; sha256: string } { const bytes = readRegular(root, path).toString("utf8"); const value = JSON.parse(bytes) as T; if (bytes !== renderT015CanonicalJson(value)) throw new Error(`T015 v3 artifact is not canonical: ${path}`); return { value, sha256: sha256T015V3(bytes) }; }
function parseEvidenceTime(value: string, label: string): number { if (!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/.test(value)) throw new Error(`${label} timestamp is not canonical UTC`); const parsed = Date.parse(value); if (!Number.isFinite(parsed)) throw new Error(`${label} timestamp is invalid`); return parsed; }
function exactEvidence(actual: unknown, expected: unknown, label: string): void { if (canonical(actual) !== canonical(expected)) throw new Error(`${label} changed or has unknown fields`); }

export type T015V3ControllerDisclosure = ReturnType<typeof buildT015V3ControllerDisclosure>;
export function buildT015V3ControllerDisclosure(root: string, plan: T015V3Plan, disclosedAt: string) { parseEvidenceTime(disclosedAt, "T015 v3 disclosure"); const pending = buildT015V3Pending(root, plan); return { schema_version: 3, evidence_version: "t015-controller-disclosure-attestation-v3", attester: "USER_CREATED_CONTROL_PLANE_MAIN_SESSION", goal_slug: "ship-fictor-track1-2026", task_key: "T015", issue_number: 17, issue_contract_sha256: T015_CONTRACT_SHA256, event_sequence: { assistant_disclosure_presented_at: disclosedAt, assistant_disclosure_text_sha256: sha256T015V3(T015_V3_RISK_TEXT), assistant_disclosure_was_presented_in_current_conversation: true, exact_scoped_approval_received_after_disclosure: false }, bindings: { plan_sha256: t015V3PlanSha256(plan), pending_disclosure_packet_sha256: sha256T015V3(renderT015CanonicalJson(pending)), risk_disclosure_evidence_sha256: pending.risk_disclosure_evidence_sha256, risk_disclosure_text_sha256: pending.risk_disclosure_text_sha256, provider_schema_evidence_sha256: pending.provider_schema_evidence_sha256, v2_forensics_sha256: pending.v2_forensics_sha256, failed_v2_journal_sha256: T015_V2_JOURNAL_SHA256, implementation_binding_sha256: pending.implementation_binding_sha256 }, scope: approvalScope(), secret_free: true } as const; }
export function validateT015V3ControllerDisclosure(value: unknown, root: string, plan: T015V3Plan): asserts value is T015V3ControllerDisclosure { if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error("T015 v3 controller disclosure is invalid"); const at = (value as { event_sequence?: { assistant_disclosure_presented_at?: unknown } }).event_sequence?.assistant_disclosure_presented_at; if (typeof at !== "string") throw new Error("T015 v3 disclosure timestamp missing"); exactEvidence(value, buildT015V3ControllerDisclosure(root, plan, at), "T015 v3 controller disclosure"); }

export type T015V3Presentation = ReturnType<typeof buildT015V3Presentation>;
export function buildT015V3Presentation(root: string, plan: T015V3Plan) { const pending = buildT015V3Pending(root, plan); const controller = canonicalFile<unknown>(root, T015_V3_CONTROLLER_DISCLOSURE_PATH); validateT015V3ControllerDisclosure(controller.value, root, plan); return { schema_version: 3, evidence_version: "t015-canonical-shard-1-disclosure-presentation-v3", secret_free: true, pending_packet_sha256: sha256T015V3(renderT015CanonicalJson(pending)), plan_sha256: t015V3PlanSha256(plan), risk_disclosure_evidence_sha256: pending.risk_disclosure_evidence_sha256, risk_disclosure_text_sha256: pending.risk_disclosure_text_sha256, provider_schema_evidence_sha256: pending.provider_schema_evidence_sha256, v2_forensics_sha256: pending.v2_forensics_sha256, failed_v2_journal_sha256: T015_V2_JOURNAL_SHA256, controller_disclosure_attestation_sha256: controller.sha256, implementation_binding_sha256: pending.implementation_binding_sha256, implementation_files: pending.implementation_files, t014_approval_sha256: T015_T014_APPROVAL_SHA256, disclosed_at: controller.value.event_sequence.assistant_disclosure_presented_at, source: "current user conversation", exact_approval_phrase_required: T015_V3_EXACT_APPROVAL_PHRASE, prior_t015_v1_or_v2_approval_inherited: false, committed_clean_runtime_binding_required: true, paid_submit_path_present: false } as const; }
export function validateT015V3Presentation(value: unknown, root: string, plan: T015V3Plan): asserts value is T015V3Presentation { if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error("T015 v3 presentation is invalid"); exactEvidence(value, buildT015V3Presentation(root, plan), "T015 v3 presentation"); }

export type T015V3ControllerApproval = ReturnType<typeof buildT015V3ControllerApproval>;
export function buildT015V3ControllerApproval(root: string, plan: T015V3Plan, presentation: T015V3Presentation, approvedAt: string, now = new Date()) { validateT015V3Presentation(presentation, root, plan); const disclosedMs = parseEvidenceTime(presentation.disclosed_at, "T015 v3 disclosure"); const approvedMs = parseEvidenceTime(approvedAt, "T015 v3 approval"); if (approvedMs <= disclosedMs || approvedMs - disclosedMs > 24 * 60 * 60 * 1000 || approvedMs > now.getTime()) throw new Error("T015 v3 approval chronology is invalid"); return { schema_version: 3, evidence_version: "t015-controller-approval-attestation-v3", attester: "USER_CREATED_CONTROL_PLANE_MAIN_SESSION", goal_slug: "ship-fictor-track1-2026", task_key: "T015", issue_number: 17, issue_contract_sha256: T015_CONTRACT_SHA256, event_sequence: { assistant_disclosure_presented_at: presentation.disclosed_at, exact_user_reply_ko: T015_V3_EXACT_APPROVAL_PHRASE, exact_user_reply_received_at: approvedAt, exact_scoped_approval_received_after_disclosure: true }, bindings: { plan_sha256: presentation.plan_sha256, disclosure_presentation_evidence_sha256: sha256T015V3(renderT015CanonicalJson(presentation)), risk_disclosure_evidence_sha256: presentation.risk_disclosure_evidence_sha256, risk_disclosure_text_sha256: presentation.risk_disclosure_text_sha256, provider_schema_evidence_sha256: presentation.provider_schema_evidence_sha256, v2_forensics_sha256: presentation.v2_forensics_sha256, failed_v2_journal_sha256: T015_V2_JOURNAL_SHA256, implementation_binding_sha256: presentation.implementation_binding_sha256 }, scope: approvalScope(), secret_free: true } as const; }
export function validateT015V3ControllerApproval(value: unknown, root: string, plan: T015V3Plan, presentation: T015V3Presentation, now = new Date()): asserts value is T015V3ControllerApproval { if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error("T015 v3 controller approval is invalid"); const at = (value as { event_sequence?: { exact_user_reply_received_at?: unknown } }).event_sequence?.exact_user_reply_received_at; if (typeof at !== "string") throw new Error("T015 v3 approval timestamp missing"); exactEvidence(value, buildT015V3ControllerApproval(root, plan, presentation, at, now), "T015 v3 controller approval"); }

export type T015V3Approval = ReturnType<typeof buildT015V3Approval>;
export function buildT015V3Approval(root: string, plan: T015V3Plan, presentation: T015V3Presentation, now = new Date()) { validateT015V3Presentation(presentation, root, plan); const controller = canonicalFile<unknown>(root, T015_V3_CONTROLLER_APPROVAL_PATH); validateT015V3ControllerApproval(controller.value, root, plan, presentation, now); const pending = buildT015V3Pending(root, plan); return { schema_version: 3, evidence_version: "t015-canonical-shard-1-approval-v3", secret_free: true, decision: "APPROVE_T015_V3_RECOVERY_12_AND_LOCK_FUTURE_CANONICAL_12_331", source: "controller approval attestation", exact_user_quote: T015_V3_EXACT_APPROVAL_PHRASE, approved_at: controller.value.event_sequence.exact_user_reply_received_at, disclosed_at: presentation.disclosed_at, plan_sha256: t015V3PlanSha256(plan), disclosure_presentation_evidence_sha256: sha256T015V3(renderT015CanonicalJson(presentation)), risk_disclosure_evidence_sha256: pending.risk_disclosure_evidence_sha256, risk_disclosure_text_sha256: pending.risk_disclosure_text_sha256, provider_schema_evidence_sha256: pending.provider_schema_evidence_sha256, v2_forensics_sha256: pending.v2_forensics_sha256, failed_v2_journal_sha256: T015_V2_JOURNAL_SHA256, controller_disclosure_attestation_sha256: presentation.controller_disclosure_attestation_sha256, controller_approval_attestation_path: T015_V3_CONTROLLER_APPROVAL_PATH, controller_approval_attestation_sha256: controller.sha256, implementation_binding_sha256: pending.implementation_binding_sha256, implementation_files: pending.implementation_files, t014_approval_sha256: T015_T014_APPROVAL_SHA256, scope: approvalScope(), prior_t015_v1_or_v2_approval_inherited: false, acknowledges_prior_approvals_not_inherited: true, committed_clean_runtime_binding_required: true, paid_submit_path_present: false } as const; }
export function validateT015V3Approval(value: unknown, root: string, plan: T015V3Plan, presentation: T015V3Presentation, now = new Date()): asserts value is T015V3Approval { if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error("T015 v3 approval is invalid"); exactEvidence(value, buildT015V3Approval(root, plan, presentation, now), "T015 v3 approval"); }

export function isT015V3Authorized(root: string, plan: T015V3Plan, now = new Date()): boolean { try { const presentation = canonicalFile<unknown>(root, T015_V3_PRESENTATION_PATH); validateT015V3Presentation(presentation.value, root, plan); const controller = canonicalFile<unknown>(root, T015_V3_CONTROLLER_APPROVAL_PATH); validateT015V3ControllerApproval(controller.value, root, plan, presentation.value, now); const approval = canonicalFile<unknown>(root, T015_V3_APPROVAL_PATH); validateT015V3Approval(approval.value, root, plan, presentation.value, now); return true; } catch { return false; } }
