import { randomUUID } from "node:crypto";
import { closeSync, constants, existsSync, fsyncSync, linkSync, lstatSync, openSync, readFileSync, rmSync, unlinkSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { atomicWriteJson } from "./filesystem";
import { T015_V3_APPROVAL_PATH, T015_V3_BINDING_PATH, T015_V3_CONTROLLER_APPROVAL_PATH, T015_V3_CONTROLLER_DISCLOSURE_PATH, T015_V3_FORENSICS_PATH, T015_V3_PENDING_PATH, T015_V3_PLAN_PATH, T015_V3_PRESENTATION_PATH, T015_V3_RISK_PATH, T015_V3_SCHEMA_PATH, buildT015V3Approval, buildT015V3Binding, buildT015V3ControllerApproval, buildT015V3ControllerDisclosure, buildT015V3Forensics, buildT015V3Pending, buildT015V3Plan, buildT015V3Presentation, buildT015V3Risk, buildT015V3Schema, isT015V3Authorized, loadT015V3Binding, renderT015CanonicalJson, renderT015V3Plan, sha256T015V3, t015V3PlanSha256, validateT015V3Approval, validateT015V3ControllerApproval, validateT015V3ControllerDisclosure, validateT015V3Presentation } from "./canonical-shard-1-recovery-v3";

const repositoryRoot = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
function option(args: readonly string[], name: string): string { const index = args.indexOf(name); const value = index < 0 ? undefined : args[index + 1]; if (!value || value.startsWith("--")) throw new Error(`missing ${name}`); return value; }
export function writeT015V3NoClobber(root: string, path: string, value: unknown): string { const target = resolve(root, path); const bytes = renderT015CanonicalJson(value); if (existsSync(target)) { if (lstatSync(target).isSymbolicLink() || readFileSync(target, "utf8") !== bytes) throw new Error("T015 v3 evidence no-clobber conflict"); return bytes; } const temporary = `${target}.tmp-${process.pid}-${randomUUID()}`; const descriptor = openSync(temporary, constants.O_CREAT | constants.O_EXCL | constants.O_WRONLY, 0o600); try { writeFileSync(descriptor, bytes); fsyncSync(descriptor); } finally { closeSync(descriptor); } try { try { linkSync(temporary, target); } catch (error) { if ((error as NodeJS.ErrnoException).code !== "EEXIST") throw error; if (lstatSync(target).isSymbolicLink() || readFileSync(target, "utf8") !== bytes) throw new Error("T015 v3 evidence no-clobber conflict"); } unlinkSync(temporary); } finally { rmSync(temporary, { force: true }); } return bytes; }

function check() { const binding = loadT015V3Binding(repositoryRoot); const risk = buildT015V3Risk(); const schema = buildT015V3Schema(); const forensics = buildT015V3Forensics(repositoryRoot); const plan = buildT015V3Plan(repositoryRoot); const pending = buildT015V3Pending(repositoryRoot, plan); const expected = [[T015_V3_BINDING_PATH, binding], [T015_V3_RISK_PATH, risk], [T015_V3_SCHEMA_PATH, schema], [T015_V3_FORENSICS_PATH, forensics], [T015_V3_PLAN_PATH, plan], [T015_V3_PENDING_PATH, pending]] as const; for (const [path, value] of expected) { const bytes = readFileSync(resolve(repositoryRoot, path), "utf8"); const rendered = path === T015_V3_PLAN_PATH ? renderT015V3Plan(plan) : renderT015CanonicalJson(value); if (bytes !== rendered) throw new Error(`tracked T015 v3 artifact changed: ${path}`); } return { plan, plan_sha256: t015V3PlanSha256(plan), pending_sha256: sha256T015V3(renderT015CanonicalJson(pending)), authorized: isT015V3Authorized(repositoryRoot, plan) }; }

export function runT015V3Preparation(args: readonly string[]): Record<string, unknown> {
  const command = args[0];
  if (command === "binding-gen") { if (args.length !== 1) throw new Error("usage: recovery-v3 binding-gen"); const binding = buildT015V3Binding(repositoryRoot); atomicWriteJson(repositoryRoot, T015_V3_BINDING_PATH, binding); return { command, binding_sha256: sha256T015V3(renderT015CanonicalJson(binding)), files: Object.keys(binding.files).length }; }
  if (command === "gen") { if (args.length !== 1) throw new Error("usage: recovery-v3 gen"); atomicWriteJson(repositoryRoot, T015_V3_RISK_PATH, buildT015V3Risk()); atomicWriteJson(repositoryRoot, T015_V3_SCHEMA_PATH, buildT015V3Schema()); atomicWriteJson(repositoryRoot, T015_V3_FORENSICS_PATH, buildT015V3Forensics(repositoryRoot)); const plan = buildT015V3Plan(repositoryRoot); atomicWriteJson(repositoryRoot, T015_V3_PLAN_PATH, plan); atomicWriteJson(repositoryRoot, T015_V3_PENDING_PATH, buildT015V3Pending(repositoryRoot, plan)); const result = check(); return { command, plan_sha256: result.plan_sha256, pending_disclosure_sha256: result.pending_sha256, authorized: result.authorized, recovery_assets: 12, future_paid_assets_locked: 320, paid_submit_path_present: false }; }
  if (command === "check") { if (args.length !== 1) throw new Error("usage: recovery-v3 check"); const result = check(); return { command, plan_sha256: result.plan_sha256, pending_disclosure_sha256: result.pending_sha256, authorized: result.authorized, recovery_assets: 12, future_paid_assets_locked: 320, paid_submit_path_present: false }; }
  if (command === "disclosure-build") { if (args.length !== 3 || args[1] !== "--disclosed-at") throw new Error("usage: recovery-v3 disclosure-build --disclosed-at <timestamp>"); const checked = check(); const controller = buildT015V3ControllerDisclosure(repositoryRoot, checked.plan, option(args, "--disclosed-at")); validateT015V3ControllerDisclosure(controller, repositoryRoot, checked.plan); writeT015V3NoClobber(repositoryRoot, T015_V3_CONTROLLER_DISCLOSURE_PATH, controller); const presentation = buildT015V3Presentation(repositoryRoot, checked.plan); validateT015V3Presentation(presentation, repositoryRoot, checked.plan); writeT015V3NoClobber(repositoryRoot, T015_V3_PRESENTATION_PATH, presentation); return { command, presentation_sha256: sha256T015V3(renderT015CanonicalJson(presentation)), authorized: false }; }
  if (command === "approval-build") { if (args.length !== 3 || args[1] !== "--approved-at") throw new Error("usage: recovery-v3 approval-build --approved-at <timestamp>"); const checked = check(); const presentation = JSON.parse(readFileSync(resolve(repositoryRoot, T015_V3_PRESENTATION_PATH), "utf8")) as unknown; validateT015V3Presentation(presentation, repositoryRoot, checked.plan); const approvedAt = option(args, "--approved-at"); const now = new Date(approvedAt); const controller = buildT015V3ControllerApproval(repositoryRoot, checked.plan, presentation, approvedAt, now); validateT015V3ControllerApproval(controller, repositoryRoot, checked.plan, presentation, now); writeT015V3NoClobber(repositoryRoot, T015_V3_CONTROLLER_APPROVAL_PATH, controller); const approval = buildT015V3Approval(repositoryRoot, checked.plan, presentation, now); validateT015V3Approval(approval, repositoryRoot, checked.plan, presentation, now); writeT015V3NoClobber(repositoryRoot, T015_V3_APPROVAL_PATH, approval); return { command, approval_sha256: sha256T015V3(renderT015CanonicalJson(approval)), authorized: true }; }
  throw new Error("usage: recovery-v3 <binding-gen|gen|check|disclosure-build|approval-build>");
}
